### ISSUE TITLE
nix output coloring gets lost

### ISSUE THREAD

**Issue by maralorn** [maralorn/nix-output-monitor#1]
If someone can tell me what's going on, that'd be great.

It could be one of two things.

1. nix decides that my pipe doesn‘t deserver color
2. Haskell Text decoding removes color codes.

The second would annoy me a lot.

**Comment by piegamesde** [comment]
As a simple test with `|& /usr/bin/less` tells, it's the first cause.

Usually, CLI applications that do color have a `color={ALWAYS|AUTO|NEVER}` parameter, but I haven't seen any on the `nix` commands. There are ways to trick an application that it should display color nevertheless, but frankly it's more a hacky workaround.

**Comment by SuperSandro2000** [comment]
I got it working with unbuffer from the expect package:

```
unbuffer nix-build -A package | nom
```
