### ISSUE TITLE
Missing/unsupported glyph(s), even with NerdFont?

### ISSUE THREAD

**Issue by x10an14** [maralorn/nix-output-monitor#103]
Hi!

I'm running nushell inside of tmux with this nerdfont installation (all installed through home-manager):
```nix
{pkgs, ...}: {
  fonts.fontconfig.enable = true;
  home.packages = [
    (pkgs.nerdfonts.override {
      fonts = ["Hasklig"];
    })
  ];
}
```

Yet, as below picture shows, there's one (or more) glyphs that don't render?
(Please notice how all other glyps, including the ones from `starship` prompt _do_ load/render).

If NerdFont doesn't support it, how/where else should we look for the glyphs `nom` intends to use? =S

<details>
<summary>Screenshot 1</summary>

![Screenshot from 2023-07-11 23-54-50](https://github.com/maralorn/nix-output-monitor/assets/710608/1798891d-35a7-4041-834f-ad6d03a4fb0a)

</details>

<details>
<summary>Screenshot 2</summary>

![Screenshot from 2023-07-11 23-58-21](https://github.com/maralorn/nix-output-monitor/assets/710608/6a77e1fe-5529-4b98-b918-dbf100a8115a)

</details>

EDIT: Above screenshots taken of gnome-terminal application running nushell inside (and outside) of tmux.

**Comment by x10an14** [comment]
Seems related to (but not really same as) #80...

**Comment by maralorn** [comment]
Hey there. Those emojis are a support nightmare. Maybe nom should bundle its font and its terminal.^^

The glyph in questions seems to be the "play" arrow.
 I am also using nerdfonts and that is actually one of the mor ecommon symbols so I have no clue why that problem is happening. Have you tried in a different terminal/without tmux maybe one of those break the encoding?

**Comment by x10an14** [comment]
<details>
<summary>Nushell w/o tmux</summary>

![Screenshot from 2023-07-13 00-39-27](https://github.com/maralorn/nix-output-monitor/assets/710608/b6a53b4e-9baa-426e-a96a-b61bc1b06044)
![Screenshot from 2023-07-13 00-39-11](https://github.com/maralorn/nix-output-monitor/assets/710608/a0401440-b1b3-49a0-b8fb-e18e61d399eb)

</details>

<details>
<summary>Bash w/o tmux</summary>

![Screenshot from 2023-07-13 00-41-09](https://github.com/maralorn/nix-output-monitor/assets/710608/3de79b6d-c268-43d0-86df-37d3b79b3acb)
![Screenshot from 2023-07-13 00-40-52](https://github.com/maralorn/nix-output-monitor/assets/710608/bcb0df65-4220-4c5e-909d-a33c9ddc5d53)

</details>

**Comment by maralorn** [comment]
Yeah, I mean it was unlikely for nushell to be the problem.

Looking at your config a bit closer. Are you actually sure your terminal is using Hasklig NerdFont? At least the part of your config that you showed does not ensure that.

**Comment by x10an14** [comment]
> Yeah, I mean it was unlikely for nushell to be the problem.

I honesly don't know enough about this to say whether it should or shouldn't =)
I thought it pertinent to show with and without, due to _always_ having to invoke `nom` through bash for the usecase of `nix flake check` on Nushell ([`complete` & stderr/stdout](https://www.nushell.sh/book/stdout_stderr_exit_codes.html#using-the-complete-command),  and [combining stdout and stderr redirection](https://www.nushell.sh/book/stdout_stderr_exit_codes.html#using-out-err-to-redirect-stdout-and-stderr-to-files)).*

> Looking at your config a bit closer. Are you actually sure your terminal is using Hasklig NerdFont? At least the part of your config that you showed does not ensure that.

Hmmm... How do I prove this (to you and me both) then?
I tried googling "How to test nerdfonts works", but got nowhere... Found this though https://github.com/ryanoasis/nerd-fonts/discussions/829, which basically says this is impossible.

These(https://nix-community.github.io/home-manager/options.html#opt-fonts.fontconfig.enable) two(https://discourse.nixos.org/t/home-manager-nerdfonts/11226/2) sources are what I used to land on said configuration.

---
* Maybe you'd want me to open up a separate github issue requesting support for `nom flake check`? Or maybe just `nom flake`?

**Comment by x10an14** [comment]
I managed to install Kitty, instead of the default gnome-terminal terminal emulator available on Linux Mint.

<details>
<summary>Does this look correct?</summary>

![Screenshot from 2023-07-13 13-33-25](https://github.com/maralorn/nix-output-monitor/assets/710608/4158102e-48e0-46bd-bbe4-d544f9d34822)

</details>

Doesn't quite look like the "play" icons you referenced here:
> The glyph in questions seems to be the "play" arrow.

**Comment by maralorn** [comment]
Yeah, please make a new issue for `nom flake`.

Yeah, the emoji also looks wrong in kitty.

I generally look very closely at the letters maybe on a big fontsize and compare them with a picture of the font online. Normally you quickly see if the font is different.

**Comment by x10an14** [comment]
Would you agree this looks identical?
I see that the `=>` is not identical, but I think that might have something to do with the animation of characters combining into a new one...
![Screenshot from 2023-07-14 10-29-23](https://github.com/maralorn/nix-output-monitor/assets/710608/732cefb5-bdc7-4fa0-9f1e-c31ca3e62c36)

**Comment by maralorn** [comment]
Yeah, ligature support (which you need for the nice implication symbol connected over two cells) in terminals is rare.

But actually I would say it is clear those two fonts are not the same: Compare e.g. the lower end of the large Q which is much more curved and longer in Hasklig. In general most letters in Hasklig look slightly more curved. Ah, now I see: the biggest difference is the small g. Definitely not the same font.

**Comment by x10an14** [comment]
Damn, you're correct. I apologize for my errant claim! Let's see if this thread is still relevant when I get it configured correctly.

**Comment by x10an14** [comment]
### I fixed it! NerdFont Hasklug is now used!

It _was_ the terminal emulator (gnome-terminal) which didn't support ligatures, and used the wrong font.

The missing yellow icons are still missing... =/

However, with the below new home-manager nix config, I believe I _am_ using the correct font.

---
<details>
<summary>Nix home-manager config leveraging nerdfont</summary>

```nix
{
  config,
  lib,
  pkgs,
  ...
}: let
  hasklugNerdFont = pkgs.nerdfonts.override {
    fonts = ["Hasklig"];
  };
in {
  fonts.fontconfig.enable = true;
  programs.kitty = lib.mkIf config.programs.kitty.enable {
    font = {
      package = hasklugNerdFont;
      name = "Hasklug Nerd Font Mono";
    };
  };
}
```

NB: Notice the `profile` comment of https://nix-community.github.io/home-manager/options.html#opt-programs.kitty.font.package!
</details>


<details>
<summary>Visual proof of Hasklug in use</summary>

![Screenshot from 2023-07-16 17-30-17](https://github.com/maralorn/nix-output-monitor/assets/710608/99d5187a-3a18-4a9d-8c3e-f8334d53af48)
</details>

**Comment by maralorn** [comment]
Congrats! Enjoy the font!

But that didn’t fix the glyphs? That is weird and unsatisfying. I am kind of at a loss what else could be the culprit …

**Comment by x10an14** [comment]
> Congrats! Enjoy the font!

Thank you! =)

---- 
> But that didn’t fix the glyphs? That is weird and unsatisfying. I am kind of at a loss what else could be the culprit …

I tried again now with non-mono font version, no change =/

**Comment by x10an14** [comment]
Adding the [`NerdFontsSymbolsOnly` font](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/NerdFontsSymbolsOnly.zip) to `kitty +list-fonts` didin't help either =/

**Comment by 999eagle** [comment]
I've also had some issues with this. The unicode character in question here, U+23F5 (⏵), is not part of NerdFonts as far as I can tell (same with the hourglass U+23F3). For me, installing Symbola using `fonts.fonts = [pkgs.symbola];` in my system configuration to have a good fallback fonts for symbols like this that are neither part of standard fonts nor emoji nor part of NerdFonts fixed the problem.

**Comment by flexiondotorg** [comment]
I ran into this issue and installing the [symbola](https://search.nixos.org/packages?channel=24.05&show=symbola&from=0&size=50&sort=relevance&type=packages&query=symbola) font has resolved it.

**Comment by x10an14** [comment]
The hourglass symbol is still missing for me (the one in orange I think?), even with symbola.otf listed in `fc-list` =/

**Comment by maralorn** [comment]
Also, nom does not use the hourglass symbol anymore. (Although I am not 100% sure that’s released, yet.)
