### ISSUE TITLE
Quiet mode

### ISSUE THREAD

**Issue by Sadaell** [maralorn/nix-output-monitor#105]
I may have missed it in the docs, but nom is really lacking a quiet mode that will silence all `evaluating file '/nix/store/...'` messages

**Comment by maralorn** [comment]
Hey! I need to figure out, what you mean here.

Does your nom print a lot of `evaluating file `/nix/store/...' lines to the log? That’s unexpected.

I’m also not sure what version you are using. Can you maybe share a screenshot example of a situation which you don’t like?

A quiet mode is a potentially good idea, but it could mean wildly different things and my aim is to have the default behavior be as a useful as possible for everybody.

**Comment by Sadaell** [comment]
I'm really sorry, writing an issue at 2am wasn't the best idea. Turns out I just forgot that an alias I was piping from has '--verbose' in it, hence the output.

**Comment by maralorn** [comment]
No problem! Feel free to open another issue if the need arises!
