### ISSUE TITLE
gracefully exit when confronted with different error conditions.

### ISSUE THREAD

**Issue by maralorn** [maralorn/nix-output-monitor#114]
SIGINT seems to be fine but SIGTERM does not work.

**Comment by Mic92** [comment]
Actually I tested. Stopping with SIGINT also causes the cursor not to be restored here.

**Comment by Mic92** [comment]
Turns out it doesn't handle any signal and closing the pipe followed by waiting for nom to exit, fixes it: https://github.com/Mic92/nix-ci-build/commit/8c84a91e40d5e9e34d698d1c6127395c25bbc209#diff-9d885e639e896c471d700b09b2d5cddc505f12f7fea6f369bce4c392b0655805R404
