### ISSUE TITLE
Trace messages are lost

### ISSUE THREAD

**Issue by viperML** [maralorn/nix-output-monitor#128]
When piping both stdout and stderr to nom, nom doesn't print back the trace messages:

```
$ nix build --no-eval-cache /home/ayats/Documents/dotfiles#nixosConfigurations."hermes".config.system.build.toplevel

trace: nix-2.18.1 reached desired version 2.14.0
trace: warning: The option `services.avahi.nssmdns' defined in `/nix/store/kfblblk8pvjbdip1c9r6k3c2abdn4d1r-source/hosts/hermes/configuration.nix' has been renamed to `services.avahi.nssmdns4'.
```

```
$ nix build --no-eval-cache --log-format internal-json /home/ayats/Documents/dotfiles#nixosConfigurations."hermes".config.system.build.toplevel |& nom --json

Finished at 19:12:48 after 7s
```

Related: https://github.com/viperML/nh/issues/64

**Comment by maralorn** [comment]
Yes, that’s a known issue, but we need to fix it. I often go far to long without noticing certain warnings.

**Comment by daniel-sampliner** [comment]
I don't know what I'm doing, but I took a crack at this in 738f445082d6d5c8f96701ccd1fe1136a7a47715.

A simple example of the output:
```
 :; nix -L --log-format internal-json eval --raw --expr 'builtins.trace "some trace message" ""' |& ./result/bin/nom --json
trace: some trace message
┏━ 1 Traces: 
┃ trace: some trace message
┣━━━                                                            
┗━ ∑ ⚠ Exited with 1 traces reported by nix at 16:47:35 after 0s
```

For a more complicated example with NixOS module warnings (which is the main thing I was originally interested in fixing):

https://github.com/maralorn/nix-output-monitor/assets/54726391/67996707-50ab-4ad7-8ff3-81f33575f396

(built from this flake: https://github.com/daniel-sampliner/nix-output-monitor/blob/nixos-warning-example/flake.nix)

**Comment by viperML** [comment]
Github says that "video can't be plated because the file is corrupt"
