### ISSUE TITLE
Can't see password prompt

### ISSUE THREAD

**Issue by erahhal** [maralorn/nix-output-monitor#133]
Using `nom` with `nixos-rebuild`, e.g.:

```
nixos-rebuild --log-format internal-json -v --use-remote-sudo switch --flake .#${HOSTNAME} -L |& nom --json
```

It eventually gets to a `sudo` prompt, but it can't be seen, because nix-output-monitor's tree is on top of it.

I believe this didn't used to be a problem, but I could be mistaken.

**Comment by maralorn** [comment]
Yeah, I think the best fix for that is integrating nom into nixos-rebuild.

Ah, I guess the problem here is --json which means that non-json get’s ignored.
But maybe we can work around that.

Besides this is a duplicate of #68.

**Comment by erahhal** [comment]
Thanks, I'll follow that issue.
