### ISSUE TITLE
Push new release

### ISSUE THREAD

**Issue by eyJhb** [maralorn/nix-output-monitor#137]
Can a new release be made, which includes the commit #128 , or generally just the latest?
Seems like quite a lot has happened since the last release tag, and the trace warnings would be VERY useful to have.

Love the project :)

**Comment by maralorn** [comment]
Yeah, sorry. I feel a bit guilty. There is still a test error on the main branch, which I keep procrastinating to investigate. Will try to get it to it soon.

**Comment by eyJhb** [comment]
No worries! That's just how it is sometimes. Didn't know about the error :) Just wanted to leave a little ping, for once you have the time.

**Comment by maralorn** [comment]
Done
