### ISSUE TITLE
Indication of failed packages

### ISSUE THREAD

**Issue by expipiplus1** [maralorn/nix-output-monitor#14]
It would be nice to keep track of this for when users are building with `-k` (staunch mode). Not sure what the UI should be exactly.

**Comment by maralorn** [comment]
That does not sound very hard with the infrastructure we already have.

Of course this would introduce a new table column (that would be my naiv approach at least), which means we should consider writing something a bit more serious for the table layout which already is a bit buggy as it is and will not become less complex when we put more features in.

**Comment by maralorn** [comment]
Fixed on master.

**Comment by expipiplus1** [comment]
Thanks!
