### ISSUE TITLE
Show size of derivation during download

### ISSUE THREAD

**Issue by PerchunPak** [maralorn/nix-output-monitor#141]
Time to time, my internet gets extremely bad (from speed of 100mb/s to 10kb/s; I fix it by switching to another wifi), so I would like to see speed of download or size of derivation during download

![image](https://github.com/maralorn/nix-output-monitor/assets/68118654/3bf911b7-0e11-4673-bf3c-3ea80da80a08)
(I am pretty sure kernel doesn't weight 5gb)

**Comment by maralorn** [comment]
Yeah, definitely. I’d say this is included in #4, which is high on my next feature list.
