### ISSUE TITLE
git.maralorn.de: NXDOMAIN

### ISSUE THREAD

**Issue by herbetom** [maralorn/nix-output-monitor#143]
There is a help text with a link:

https://github.com/maralorn/nix-output-monitor/blob/f7a37d3c39cee5fbb37edf5ded45840ee8c932b5/exe/Main.hs#L214-L215

but there isn't even an DNS Record for that domain:

```
$ host git.maralorn.de
Host git.maralorn.de not found: 3(NXDOMAIN)
```

**Comment by Atemu** [comment]
It's https://code.maralorn.de/maralorn/nix-output-monitor now.

**Comment by maralorn** [comment]
Thank you.

Fixed on main.
