### ISSUE TITLE
FeatureRequest: Display "evaluating derivation" state

### ISSUE THREAD

**Issue by luochen1990** [maralorn/nix-output-monitor#148]
Evaluation stage might take 1 minute or longer, nothing displayed during this time is very confusing.

In particular, when used in this way `sudo nixos-rebuild switch |& nom`, I am completely unable to determine whether it is waiting for a password input or evaluating

**Comment by SuperSandro2000** [comment]
You probably want to use a patch like https://github.com/NixOS/nixpkgs/commit/38291ead98c0186473aa75bc38df465851dde490 instead of piping into nom

**Comment by luochen1990** [comment]
> You probably want to use a patch like [NixOS/nixpkgs@38291ea](https://github.com/NixOS/nixpkgs/commit/38291ead98c0186473aa75bc38df465851dde490) instead of piping into nom

I think things like `nh` should also inherit this feature, so it's not just about `nixos-rebuild` IMHO

**Comment by maralorn** [comment]
I think it is a valid request (no matter the specific context) and I actually had this at some point, sadly there were bugs in the implementation so I never released it.

**Comment by maralorn** [comment]
Planning to this as part of #73.
