### ISSUE TITLE
Icons don't match screenshot / readme

### ISSUE THREAD

**Issue by RubikCubed** [maralorn/nix-output-monitor#157]
I went to look up what some of the icons meant and noticed the icons in the screenshot + readme don't match the output anymore, were they updated at some point?
Or are my fonts acting up?

eg
1. The ⏳︎︎︎ is now a ⏸
2. I don't see ⏵ anywhere

**Comment by maralorn** [comment]
Good point, we should fix that.

**Comment by maralorn** [comment]
I think partially github displays the emoji differently …

**Comment by maralorn** [comment]
I am quite certain that ⏵appears when builds are running.

**Comment by RubikCubed** [comment]
> I am quite certain that ⏵appears when builds are running.

Yep, I've just confirmed that myself. Thanks for the other changes :)
