### ISSUE TITLE
NOM shows incorrect amount of simultaneous builds when using Lix

### ISSUE THREAD

**Issue by PerchunPak** [maralorn/nix-output-monitor#159]
I noticed this problem long before, just was too lazy to report

```sh
~ ❯ nom --version
nix-output-monitor 2.1.3
nix (Lix, like Nix) 2.92.0-dev-pre20241012-a322fce
~ ❯ nixos-version
24.11.20241013.d2d9d9f (Vicuna)
```

![image](https://github.com/user-attachments/assets/f51dfb38-9ea3-4a09-94c4-3be0f0ca06fb)

**Comment by PerchunPak** [comment]
Though sometimes it works fine
![image](https://github.com/user-attachments/assets/4ed66b1d-d9f5-4d6f-bc17-f745b1219fae)

**Comment by maralorn** [comment]
I suspect this to be a duplicate of #144.

**Comment by PerchunPak** [comment]
Don't see this issue anymore

**Comment by maralorn** [comment]
Ah, yeah, It could be that lix fixed this on their side.
