### ISSUE TITLE
Option to show last derivation name

### ISSUE THREAD

**Issue by expipiplus1** [maralorn/nix-output-monitor#16]
Sometimes I'll kick off several nix builds in tmux panes, and then later forget which one is which. It would be nice if nom could keep a reminder of the last derivation (perhaps this could be guarded by an option, because it probably isn't necessary all the time).

Another option would be to capture the nix command line args and keep them on the screen, so instead of `nix-build ... |& nom` one could run `nom -- nix-build ...`

**Comment by maralorn** [comment]
I have the feeling, that the listing of planned builds at the start of a build is sorted by dependence. i.e. the last derivation will be what the user actually wants. So I think displaying that somewhere would be nice. I have an idea how to do that, but that is something else that probably should be done after improving the output formatting code.

I am uncertain about the wrapper idea in general. It would be mightier but less composable.

**Comment by expipiplus1** [comment]
The wrapper would allow one to do `nom -- !!` after forgetting to append it!

**Comment by expipiplus1** [comment]
> I have the feeling, that the listing of planned builds at the start of a build is sorted by dependence. i.e. the last derivation will be what the user actually wants

True only if the user requested a single thing!

**Comment by maralorn** [comment]
This is implemented on master.

**Comment by expipiplus1** [comment]
Thanks!
