### ISSUE TITLE
Save build times and show estimation

### ISSUE THREAD

**Issue by SuperSandro2000** [maralorn/nix-output-monitor#17]
It would be super awesome if we could collect the times per package and machine and try to estimate a rough time it will take. It does not need to be exact on the minute or 5 but showing if it takes 5 minutes or 5 hours would already be pretty awesome. Sadly I don't know Haskell at all so I can't provide a PR.

**Comment by maralorn** [comment]
It’s definitely a nice idea.

**Comment by maralorn** [comment]
I have implemented this on master.
When the (host, pname) pair has been seen before we display a moving average over the build times.

**Comment by SuperSandro2000** [comment]
I will try this out after the PR got merged and give you feedback if it is totally off or works about right.

**Comment by takeda** [comment]
@maralorn does recompiling need to happen in a single run? The reason I'm asking is that I'm currently bisecting nixpkgs and recompiling it, but estimates aren't showing up. I saw it briefly once though, so it sometimes works, but I don't know how make NOM do it more.

**Comment by maralorn** [comment]
@takeda No, it’s supposed to be persistent between runs. Sadly I have no sensible tests and very rudimentary error handling for this feature. I have the feeling that I broke it at same point. I plan a complete refactor and improvement of the stats and predictions.
