### ISSUE TITLE
Dump logs to file

### ISSUE THREAD

**Issue by SCOTT-HAMILTON** [maralorn/nix-output-monitor#18]
Could we have a -l option to dump the logs to a file.

**Comment by maralorn** [comment]
Hey @SCOTT-HAMILTON.

Is this really a necessary feature in nom?
I think you can achieve that with
```
  nix-build |& tee my-build.log | nom
```
Also there are also multiple ways for nix to show or keep different logs. (Which has the huge advantage of showing a log per build, not the giant clobbered log nom sees.)

Or do you have a usecase in mind that I didn‘t think of?

**Comment by SCOTT-HAMILTON** [comment]
Yes you're right it's better to use nix logs.
