### ISSUE TITLE
Put on hackage & stackage & nixpkgs

### ISSUE THREAD

**Issue by turion** [maralorn/nix-output-monitor#2]
If you add this to hackage & stackage, it will automatically appear in nixpkgs, making installation a lot easier for nix users.

**Comment by maralorn** [comment]
Thanks for the hint. (It wouldn‘t need to be in stackage as long as I pay a bit attention to version bounds.) I am just not sure that it is a good idea.

I feel a program with this functionality shouldn’t even exist. It's a hack to fight short comings that could much better be implemented in nix.

Besides that putting it on hackage implies a certain commitment to maintaining this in the future.

I guess I am a bit conservative here. I am open to be convinced otherwise.

**Comment by turion** [comment]
> I feel a program with this functionality shouldn’t even exist. 

Haha, yes. Maybe you can talk to the https://github.com/haskell-nix/hnix people and convince them to adopt something like your output scheme? Or contribute it yourself to their project?

> Besides that putting it on hackage implies a certain commitment to maintaining this in the future.

Hmm I personally don't consider hackage packages to be up to date, or working, or maintained. If I want to know whether something is maintained actively, I look at stackage. But that's a subjective matter, I guess.

I understand that maybe you don't want `nom` to have great adoption, but you rather want to have a positive example to tell nix developers what to aim for.

**Comment by maralorn** [comment]
> Hmm I personally don't consider hackage packages to be up to date, or working, or maintained. If I want to know whether something is maintained actively, I look at stackage. But that's a subjective matter, I guess.

I am not sure how subjective this is. It might just be, that my perspective is "how it should be" and yours is "how it is". Curious about what others think of this.

> I understand that maybe you don't want `nom` to have great adoption, but you rather want to have a positive example to tell nix developers what to aim for.

Well, if you phrase it that way, I don‘t think that's my point. I‘d like for nom to have great adoption (temporarily). I‘d love for people to profit of my work and I think a large adoption would be a sign for the desire to have those features.

Also first and foremost this is not about me telling the nix developers how to do their job. I primarily wrote this tool for me. If this has any impact for others, I‘d love that. But it was definitely not meant as "this is how it must be done".

**Comment by maralorn** [comment]
@turion What do you think about just putting it into nixpkgs? I don‘t think anyone would want to install it any other way or want to use it as a Haskell lib. And for me it would mean roughly the same if not less maintenance work.

**Comment by turion** [comment]
> I am not sure how subjective this is. It might just be, that my perspective is "how it should be" and yours is "how it is". Curious about what others think of this.

I think it's fine to have a database of packages that aren't actively maintained. Because sometimes forking an old abandoned project is better than rewriting one from scratch, at least in Haskell. And also so we don't forget what work has been done already and be inspired by it. That being said, the best thing in my opinion was if Hackage & Stackage were one thing, and all packages are listed there, with their current build status. But alas, that's not the case.

> Well, if you phrase it that way, I don‘t think that's my point. I‘d like for nom to have great adoption (temporarily). I‘d love for people to profit of my work and I think a large adoption would be a sign for the desire to have those features.

Ah ok good that I asked :) well I'd like to use it but didn't bother yet because I didn't want to think about how to install it.

> What do you think about just putting it into nixpkgs?

Sounds ok, if you know how you can get it well into nixpkgs without putting it elsewhere. One of my main reason for using stackage for all of my package is a free CI. If you put it in nixpkgs without putting it on hackage, or stackage, you're losing that to certain degrees. If it's not on stackage, you won't be notified on stackage when it breaks with the up-to-date ecosystem. If it's not even on hackage, it probably won't be marked as broken in nixpkgs when it breaks with the nixpkgs set. If you put it on stackage, you can still choose not to update it, but at least you (and everyone who cares) will be notified.

If you want someone who looks after the package from time to time and makes the odd PR to keep it up to date, that could be me.

**Comment by maralorn** [comment]
Since nom is now in nixpkgs, I think this is done.
