### ISSUE TITLE
Support for nix v2 "internal-json" output.

### ISSUE THREAD

**Issue by maralorn** [maralorn/nix-output-monitor#26]
Relying on that sounds brittle but it would improve our options a lot because it has much more information.

**Comment by maralorn** [comment]
We can now parse internal-json on master.

i.e. `nix build -v --log-format internal-json |& nom`
even better you can now do `nom build` for the same effect and with better exception + exit code handling.

I will only release this when nix 2.10 is out, because I want users to experience this together with https://github.com/NixOS/nix/pull/6620

**Comment by dpc** [comment]
```
> nix --version
nix (Nix) 2.10.3
```

Time to release?

**Comment by maralorn** [comment]
Oh, nice.

Sadly, there are at least two regressions I need to fix first. Additionally, my life is exceptionally busy right now, so this might need to wait until autumn. Sorry about that. I will get back to this at some point!
