### ISSUE TITLE
hGetContents: illegal operation

### ISSUE THREAD

**Issue by brent80** [maralorn/nix-output-monitor#27]
This is on Ubuntu with nix package installer
Installed with nix-env -f default.nix -i
When I use nom I get this error
nom: <stdin>: hGetContents: illegal operation (handle is semi-closed)

Not sure why, another person with nixOS runs the same command in the same repo and it works for them.

**Comment by maralorn** [comment]
I have been getting this report once in a while since this program exists. I have tried some mitigations, which fix some cases, but some others apparently not …

**Comment by maralorn** [comment]
Duplicate of #23
