### ISSUE TITLE
Support monitoring nix-shell builds

### ISSUE THREAD

**Issue by ramirez7** [maralorn/nix-output-monitor#30]
I recently bumps my deps for a project and had a lot of building, so I used `nom` to track it.

The first thing I did was `nix-shell`. Piping into `nom` worked fine..until it came time to be in the shell.

It wasn't a big deal. I just `nix-shell`ed again without `nom`. But it would be nice if `nom` supported monitoring and then dropping into the `nix-shell` correctly. My guess is the normal `|&` piping won't work though.

**Comment by maralorn** [comment]
Yeah, I am certainly aware of this shortcoming. Sadly I am not sure what a good solution for this would be.
I have a few ideas but none are really convincing.

**Comment by piegamesde** [comment]
`nom-shell`?

**Comment by maralorn** [comment]
> `nom-shell`?

I mean that’s a funny name but did you actually imply a technical solution? I am still not sure how we can achieve this.

**Comment by piegamesde** [comment]
I may be naive, but I honestly don't know the difficulty behind this. Shouldn't `alias nom-shell="nom-build shell.nix || nix-shell"` already work?

**Comment by maralorn** [comment]
Nearly. I mean nix-shell only builds the dependency of a derivation not the derivation itself.
Also it would be nice to have this work for all kinds of different defaults. e.g. nix-shell will take default.nix if shell.nix is not precent.

**Comment by maralorn** [comment]
The current flake on master contains working

`nom-shell`
`nom shell`
and `nom develop` commands.

They will be contained in the next release.

They are a little bit dirty hacks, because they call the shell twice, but they work. (And in this special case the flake evaluation caching is pretty useful.)
