### ISSUE TITLE
Tab completion

### ISSUE THREAD

**Issue by mweinelt** [maralorn/nix-output-monitor#31]
The biggest regression from using plain nix is that we don't have tab completion anymore. Do we have  someone who is familiar with that kind of thing to make `nom-build` feel more like a drop-in replacement for `nix-build`?

**Comment by maralorn** [comment]
I need to do more research to modify the nixpkgs expression to "just do the  right thing".

Until then in zsh you can put `compdef nom-build=nix-build` in your zshrc.

**Comment by SuperSandro2000** [comment]
For bash:

```bash
complete -F _nix_completion nom-build
```

I already started something https://github.com/hedning/nix-bash-completions/pull/16 but I can't remember if that fully worked or was half broken.

**Comment by maralorn** [comment]
As of https://github.com/NixOS/nixpkgs/pull/163441 we have zsh completion support in nixpkgs.

**Comment by maralorn** [comment]
> For bash:
> 
> ```shell
> complete -F _nix_completion nom-build
> ```

I have just tried that command in a quick bash I started. That apparently didn’t work. Not sure what’s wrong.

**Comment by SuperSandro2000** [comment]
> I have just tried that command in a quick bash I started. That apparently didn’t work. Not sure what’s wrong.

Either bash-completion loads things async and you first need to load the nix completion function or my patch is really necessary.
I have aliases nom to nix-build so everything just worked.

**Comment by maralorn** [comment]
With the new bunch of commands introduced now:

- [ ] `nom-shell`
- [ ] `nom build`
- [ ] `nom develop`
- [ ] `nom shell`

There is more todo on completion.

**Comment by maralorn** [comment]
Fixed around #151
