### ISSUE TITLE
Path of package in outputs unexpected 

### ISSUE THREAD

**Issue by SuperSandro2000** [maralorn/nix-output-monitor#32]
After 4bd9d76712dc69f87a854fd3fb93afa00921ddfd I needed to apply the following diff to my home comfiguration after tinkering a bit around because I expected the output path to be ``nix-output-monitor.packages.default."${system}"``. I think `flake-utils.lib.eachSystem` is not handling the new structure well.

```diff
--- a/.config/nixpkgs/flake.nix
+++ b/.config/nixpkgs/flake.nix
@@ -61,7 +61,7 @@
             nixpkgs.overlays = [
               (final: prev: {
                 comma = import comma { };
-                nix-output-monitor = nix-output-monitor.defaultPackage."${system}";
+                nix-output-monitor = nix-output-monitor.packages."${system}".default;
                 nix-update = import nix-update { };
                 nixpkgs-hammering = nixpkgs-hammering.defaultPackage."${system}";
```

**Comment by maralorn** [comment]
I was following the deprecation warning thrown by nix 2.7.

I’ll clumsily screenshot it from [the “what's new” video](https://www.youtube.com/watch?v=TzQpmDrnRQA):

![image](https://user-images.githubusercontent.com/1651325/159463487-5d1e0b53-386e-4d22-b683-bd83aaf1091c.png)

I think `nix-output-monitor.packages."${system}".default` is actually what it’s supposed to be in the future.
