### ISSUE TITLE
Display job's system architecture when it differs from the goal derivations platform

### ISSUE THREAD

**Issue by mweinelt** [maralorn/nix-output-monitor#34]
An example would be having to build two version of nss, one for i686-linux and one for x86_64-linux, which happens when you're building wine-wow. It would be neat to have this information more easily visible.

**Comment by maralorn** [comment]
What do you think about a different but easier to implement idea: Display the job’s system architecture whenever there are two jobs with different architecture?

**Comment by mweinelt** [comment]
Yeah, I think that is indeed easier to develop and should provide the same clarity.

**Comment by maralorn** [comment]
On the current main branch, the architecture of build is appended to a build name, when it is not the architecture we are running on. I think this will suffice for now.
