### ISSUE TITLE
GHC 9.2.2 got removed from nixpkgs master

### ISSUE THREAD

**Issue by SuperSandro2000** [maralorn/nix-output-monitor#37]
https://github.com/maralorn/nix-output-monitor/blob/main/flake.nix#L26= causes an eval error because nixpkgs master switched to 9.2.3 https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/release-haskell.nix#L55=

**Comment by maralorn** [comment]
fix pushed to master

**Comment by SuperSandro2000** [comment]
Thanks!
