### ISSUE TITLE
Build time counter should be paused while system is suspended

### ISSUE THREAD

**Issue by alyssais** [maralorn/nix-output-monitor#46]
I had some builds running while my computer was suspended for several hours.  When I woke it up, nom was showing very high build times for things that should have finished quickly, presumably because it was counting time that had elapsed while the system was suspended.

This sort of issue is usually caused by using wall clock time (`CLOCK_REALTIME`) instead of the monotonic clock (`CLOCK_MONOTONIC`), which at least on Linux does not increment while the system is suspended.   `CLOCK_REALTIME` is also affected by system time changes, so if that is what nom is using, it would be possible to have negative build times if the clock went back (e.g. DST).

There seem to be Haskell packages for using the monotonic clock.

**Comment by maralorn** [comment]
I had been using UTCTime, so negative build times were not on the menu, but suspending is an issue, I agree.

I have just pushed a fix, will be included in the next release.
