### ISSUE TITLE
Make it super clear that the build succeeded.

### ISSUE THREAD

**Issue by NorfairKing** [maralorn/nix-output-monitor#50]
The difference between a failing build and a succeeding build is not so big.
It would be great if the build could end with a red or a green message.

**Comment by maralorn** [comment]
I assume that you are using the latest release of nix-output-monitor?

I think the current version on main does what you want. Sadly, I am not prepared to do a release right now because of some regressions, and I am a bit bogged down at the moment.

**Comment by NorfairKing** [comment]
That's right, no hurries though, this is a very minor inconvenience.

**Comment by maralorn** [comment]
I am going to make a new release soonish. I am going to close this, because I believe the display is very clear on master. If you are not satisfied with the display of (the to be released) nom 1.2, then please open another issue.
