### ISSUE TITLE
Do not use IFD

### ISSUE THREAD

**Issue by NobbZ** [maralorn/nix-output-monitor#57]
The flake as it is right now is not buildable on systems that have IFD disabled:

```
$ nix shell github:maralorn/nix-output-monitor
error: cannot build '/nix/store/0cbm1lh605609ikw5q9j5vdvj1przbab-cabal2nix-nix-output-monitor.drv' during evaluation because the option 'allow-import-from-derivation' is disabled
(use '--show-trace' to show detailed location information)
```

**Comment by NobbZ** [comment]
Indeed I'm interested in the new `nom shell` commands, therefore I'm trying to build from the flake.

I can generally circumvent the problem temporarily for an ephemeral installation, though in general IFD makes your flake not-inspectable as soon as you implement more than one system.

An example can be seen in https://github.com/NixOS/nix/issues/6985.

**Comment by maralorn** [comment]
I am open for further discussion on this, but as it stands I would rather not change the flake.

**Comment by SuperSandro2000** [comment]
Using IFD and hydra is a really bad combination. The hydra evaluator basically builds the IFD input at eval time which can take a few hours when cache is missing after a staging-next merge and for example gcc.arch/gcc.tune are set.

**Comment by maralorn** [comment]
I don’t like at all that the ecosystem forces everyone into not using IFD. IFD is a perfectly fine feature, and I consider the troubles it generates bugs on the consumer side. Nevertheless, I have to admit that fixing this in the flake is the way of least resistance. I will try to fix this when I get to it or accept a pull request.

**Comment by SuperSandro2000** [comment]
> IFD is a perfectly fine feature

I need to add a * onto that: If it does not cause builds of long taking builds like ghc. :/

**Comment by maralorn** [comment]
I see how that is a problem with the different stages of hydra, but in general you need the ghc to build the package anyway …

**Comment by maralorn** [comment]
I have removed the IFD. nix flake show now works.
