### ISSUE TITLE
Todo symbol not displaying

### ISSUE THREAD

**Issue by SuperSandro2000** [maralorn/nix-output-monitor#6]
I am using JetBrains Mono with NerdFonts as a fallback font and the symbol for the todo count is just a square box. Is this a configuration error on my side? Is this symbol not available in my configuration? Would it be possible to switch to something else which is displayed on more systems? All other symbols are displaying fine including my powerline so nerdfonts is most likely working correctly.

**Comment by maralorn** [comment]
Well, I could declare this as "works as intended". The symbol I use is `todo = "☐"` which _is_ just an empty square. For me it symbolized an unchecked checkbox (which is roughly the unicode meaning of this symbol see: https://unicode-table.com/en/2610/).

That being said, I expected this to be a little bit unintuitive, so I am open to any suggestions for other symbols.

**Comment by SuperSandro2000** [comment]
How about the hourglass? ⌛⏳

**Comment by maralorn** [comment]
That's a good idea. sadly. It it seems to be two characters wide, which breaks the layout.

**Comment by SuperSandro2000** [comment]
How about those? ⏱️⏲️

Alternatively the layout could be fixed.

**Comment by maralorn** [comment]
Since we are already using the stopwatch for something else, I don‘t think that will work quite right. Yeah, I will try to change the layout.

**Comment by maralorn** [comment]
I have the nagging feeling that this might break the layout even more for people how don‘t have that symbol, because their font/terminal doesn‘t know it's two characters wide?

But anyways let's give it a shot.

**Comment by SuperSandro2000** [comment]
> I have the nagging feeling that this might break the layout even more for people how don‘t have that symbol, because their font/terminal doesn‘t know it's two characters wide?

Yeah, not all terminals support emojis but then the other emojis are broken too right?

BTW before this commit 
![image](https://user-images.githubusercontent.com/7258858/96312581-2ddc5b00-100c-11eb-9a36-be5f479ec8d1.png)

and after 

![image](https://user-images.githubusercontent.com/7258858/96337236-d67ad100-1085-11eb-8979-1d1a96868deb.png)

**Comment by maralorn** [comment]
Urks. I fear that this whole emoji business is a terrible rabbit hole.

**Comment by maralorn** [comment]
Too me it looks like this.

![img](https://i.imgur.com/l5zOMoG.png)

I am not sure where to go from here …

But your output is really confusing for me. It means that apparently your hourglass has width three.
Can you confirm that by selecting? Otherwise you don‘t seem to be using all the changes I made.

**Comment by SuperSandro2000** [comment]
I took the second screenshot with a ``nix-build |& nom`` as a command.

With ``home-manager switch`` it looks better

![image](https://user-images.githubusercontent.com/7258858/96349993-6a16c680-10b3-11eb-890b-681fdbb49853.png)

I use noto-color-emoji for my emojis and this fontconfig

``~/.config/fontconfig/conf.d/99-emoji.conf ``
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
 <alias>
   <family>sans-serif</family>
   <prefer>
     <family>Noto Sans</family>
     <family>Noto Color Emoji</family>
     <family>Noto Emoji</family>
     <family>DejaVu Sans</family>
   </prefer>
 </alias>

 <alias>
   <family>serif</family>
   <prefer>
     <family>Noto Serif</family>
     <family>Noto Color Emoji</family>
     <family>Noto Emoji</family>
     <family>DejaVu Serif</family>
   </prefer>
 </alias>

 <alias>
  <family>monospace</family>
  <prefer>
    <family>Noto Mono</family>
    <family>Noto Color Emoji</family>
    <family>Noto Emoji</family>
   </prefer>
 </alias>
</fontconfig>
```

**Comment by maralorn** [comment]
Okay. I can‘t for the life of me imagine that there would be a difference between nix-build and home-manager switch.

Can you reproduce a case with a broken misaligned cell border? If not I think I'll leaf it as it is for now, because I can‘t think of anything better.

**Comment by SuperSandro2000** [comment]
> Can you reproduce a case with a broken misaligned cell border? 

This happens if nix-build only downloads things and requires to download something additionally for the package you want to build. 

![image](https://user-images.githubusercontent.com/7258858/96364129-6463c400-1139-11eb-801d-480c3f60f822.png)

**Comment by maralorn** [comment]
Ooooh, I think that's a completely unrelated bug. Good catch, will try to reproduce it.

**Comment by maralorn** [comment]
Thank, you again. Fixed on master. Will push a new release to nixpkgs, too. Because that looks ugly and concerns a very common use case.
