### ISSUE TITLE
Running in Emacs eshell crashes nom

### ISSUE THREAD

**Issue by wolverian** [maralorn/nix-output-monitor#66]
```
$ nom develop

nom: divide by zero
$ nom --version
nix-output-monitor 2.0.0.2
nix (Nix) 2.11.1
```

I think I've seen this before with some other programs when running in a terminal that doesn't provide terminal size information or something like that. Eshell is a "dumb" terminal. Of course nom won't probably work in a dumb terminal very well in the end, but I think it shouldn't crash with a divide by zero either.

**Comment by maralorn** [comment]
Thank you for reporting this! nom can deal with a terminal not reporting size, but in this case the terminal reports a size of zero.

Anyway, I have audited all cases of division in the code and made sure that divisions by zero won’t happen again.

That means this issue will be resolved in the next release.
