### ISSUE TITLE
nom develop with command throws ParseNixJSONMessageError SIMDException

### ISSUE THREAD

**Issue by ners** [maralorn/nix-output-monitor#69]
If `nom develop` is issued with `--command`, e.g.:

```
nom develop nixpkgs#hello --command gcc --version
```

it then fails to handle the output correctly and throws an error:

```
nix-output-monitor error: ParseNixJSONMessageError "SIMDException (DocumentError {path = \"\", errorMsg = \"A JSON document made of a scalar (number, Boolean, null or string) is treated as a value. Use get_bool(), get_double(), etc. on the document instead. \", docLocation = \"\", docDebug = \"\"})" "error: unrecognized command-line option \226\128\152--command\226\128\153; did you mean \226\128\152--common\226\128\153?"
```

Tested with nom 2.0.0.3 and nix 2.11.0

**Comment by maralorn** [comment]
Yeah, thank you. I am aware of the issue. It is caused by overzealous optimization attempts I did.
I will try to fix it within the next weeks.

**Comment by maralorn** [comment]
There were actually two bugs in this report and I have fixed both of them.
I have one other issue to tackle, then I will make a new release.

**Comment by ners** [comment]
Thank you @maralorn, your work is greatly appreciated. :slightly_smiling_face:
