### ISSUE TITLE
Add little --help with a small legend and explanation

### ISSUE THREAD

**Issue by maralorn** [maralorn/nix-output-monitor#7]
A `--help` command seems a bit overkill since right now, we don‘t have any flags or options, but I think a `--version` would not hurt and a little legend what the symbols we use mean, would be nice.

**Comment by expipiplus1** [comment]
I was just looking for `--help`. I found the tool while browsing `all-packages.nix` and assumed it would do some fancy daemon interrogation, but running `nom`, `nom -h` and `nom --help` all did nothing! Certainly not overkill

**Comment by maralorn** [comment]
Thanks for the feedback, I'll get to it, next time I work on this.
