### ISSUE TITLE
Does not work on --check

### ISSUE THREAD

**Issue by mweinelt** [maralorn/nix-output-monitor#8]
Checks start with this line:

> checking outputs of '/nix/store/ssbg0zrxw5qigiiai438jar05mhbllgk-python3.8-astral-2.2.drv'...  

I get no indicator whatsoever.

**Comment by maralorn** [comment]
Adding this might be a bit more involved.

It would require more parsing, potentially an extension to the state datatype and a way to detect if a check is still running.

Since I rarely use this feature I don‘t think I'll invest work into this.

**Comment by maralorn** [comment]
This is fixed on master.
