### ISSUE TITLE
Longrunning build (24h+) display runtime wrong

### ISSUE THREAD

**Issue by NobbZ** [maralorn/nix-output-monitor#85]
I am currently `git bisect`ing `nixpkgs` `master` and therefore have some huge rebuilds.

This screenshot was made roughly 24.5h after starting the build. It seems as if the days are cut off in the display.

![image](https://user-images.githubusercontent.com/58951/224115688-a514603b-08f2-4862-9b55-79dc921f265e.png)

I have not yet seen an individual build taking that long.

```text
$ nom --version
nix-output-monitor 2.0.0.5
nix (Nix) 2.15.0pre20230302_8730d30
```

**Comment by maralorn** [comment]
This is a great bug! Thank you! I totally admit that I never expected anyone to build more than 1 day. I am on maintenance hiatus, but I will get to it in time.

**Comment by NobbZ** [comment]
I took the freedom to create a PR.
