### ISSUE TITLE
nom build hides warnings

### ISSUE THREAD

**Issue by maralorn** [maralorn/nix-output-monitor#91]
https://github.com/NixOS/nixpkgs/pull/206719#issuecomment-1515368222

**Comment by maralorn** [comment]
I have witnessed this myself. Will need to figure out what is causing this.

**Comment by blaggacao** [comment]
I think this is related to https://github.com/maralorn/nix-output-monitor/issues/92

**Comment by ConnorBaker** [comment]
I just ran into this: https://github.com/NixOS/nixpkgs/pull/249259#issuecomment-1723496879

Unfortunate given that the warnings in that case were supposed to be informative to the end-user about why a package was marked as broken.

**Comment by maralorn** [comment]
I think this issue is fixed in 2.1.3. Feel free to reopen.
